#!/bin/sh -e

#TODO: cosmic-term man file
update-alternatives --install /usr/bin/x-terminal-emulator \
  x-terminal-emulator /usr/bin/cosmic-term 40 --slave \
  /usr/share/man/man1/x-terminal-emulator.1.gz x-terminal-emulator.1.gz \
  /usr/share/man/man1/cosmic-term.1.gz
